# Generated by Django 4.2.3 on 2023-07-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
